// EXPECTED_RESULT: "exception with a clear message"
log(1, 2)
